### ISSUE TITLE
fluid-testem depends on version of nyc which depends on y18n with high security vulnerability

### ISSUE THREAD

**Issue by amb26** [GPII/gpii-testem#29]
Here's the audit report:

````
  High            Prototype Pollution
  Package         y18n
  Dependency of   fluid-testem [dev]
  Path            fluid-testem > nyc > yargs > y18n
  More info       https://npmjs.com/advisories/1654

  High            Prototype Pollution
  Package         y18n
  Dependency of   nyc [dev]
  Path            nyc > yargs > y18n
  More info       https://npmjs.com/advisories/1654
````

Path to the dependency is 
````
$ npm ls y18n
infusion@3.0.0 E:\source\gits\infusion-master
+-- fluid-testem@2.1.13
| `-- nyc@15.1.0
|   `-- yargs@15.4.1
|     `-- y18n@4.0.0  deduped
`-- nyc@15.1.0
  `-- yargs@15.4.1
    `-- y18n@4.0.0
````

Looks like there is no more recent version of nyc and so I imagine this can't be resolved without moving the consumer, e.g. infusion, onto a checked-in package-lock file

**Comment by duhrer** [comment]
`npm audit` no longer reports this error. It seems like the use of looser version requirements has allowed a fixed version of y18n (`4.0.3`) to bubble back up to `yargs` and then `nyc`.

**Comment by duhrer** [comment]
Also, just a side note, I have taken to performing CI audit runs with something like `npm audit --production`, so that only security issues with non-dev dependencies are reported.  Given that's what we're carrying along to downstream users, that seems fair to me.

**Comment by duhrer** [comment]
I'm going to close this one out, as even `npm audit` without the `--production` flag no longer reports this.  Looking at the same `npm ls` command, it looks like they use flexible versions for their dependencies and picked up an improved version of  `y18n`:

```shell
➜  fluid-testem git:(main) npm ls y18n
fluid-testem@2.2.2 /Users/duhrer/Source/fluid/fluid-testem
└─┬ nyc@15.1.0
  └─┬ yargs@15.4.1
    └── y18n@4.0.3 
```
